apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotel-data-pvc
  namespace: hotel-booking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data-pvc
  namespace: hotel-booking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-data-pvc
  namespace: hotel-booking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
