apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: hotel-booking
data:
  SERVICE_PORT: "8000"
  HOTEL_SERVICE_URL: "http://hotel-service.hotel-booking.svc.cluster.local:8000"
  USER_SERVICE_URL: "http://user-service.hotel-booking.svc.cluster.local:8000"
  BOOKING_SERVICE_URL: "http://booking-service.hotel-booking.svc.cluster.local:8000"
  LOG_LEVEL: "INFO"
