apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-service-config
  namespace: hotel-booking
data:
  SERVICE_PORT: "8000"
  DATABASE_URL: "sqlite:////app/data/hotel_service.db"
  LOG_LEVEL: "INFO"
  RABBITMQ_URL: "amqp://guest:guest@message-broker-service.hotel-booking.svc.cluster.local:5672/"
