apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  namespace: hotel-booking
  labels:
    app: hotel-service
spec:
  type: ClusterIP
  selector:
    app: hotel-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
